T-Systems-MMS/skoop-webapp

src/app/users/user-profile.component.html
src/app/users/user-profile.component.spec.ts
src/app/users/user-profile.component.ts
src/app/users/user-request.ts
src/app/users/users.service.spec.ts
src/app/users/users.service.ts

Hi Georg. Could you please review this PR after 6th of January? :smile:

Additional user profile properties

---

src/app/users/user-profile.component.html
src/app/users/user-profile.component.spec.ts
src/app/users/user-profile.component.ts

@LebedkoDmitry Could you please review my implementation?

Split 'Save settings' button to 'Save user details' and 'Save permissions' buttons

---

src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.module.ts
src/app/search-users/anonymous-user-skill.ts
src/app/search-users/current-skill-level.ts
src/app/search-users/search-users.component.html
src/app/search-users/search-users.component.scss
src/app/search-users/search-users.component.spec.ts
src/app/search-users/search-users.component.ts
src/app/search-users/search-users.service.spec.ts
src/app/search-users/search-users.service.ts

Anonymous user profiles for specific skill requirements

---

src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.module.ts
src/app/my-skills/my-skills-edit.component.spec.ts
src/app/my-skills/my-skills-edit.component.ts
src/app/my-skills/my-skills.component.html
src/app/my-skills/my-skills.component.scss
src/app/my-skills/my-skills.component.spec.ts
src/app/my-skills/my-skills.component.ts
src/app/other-user-profiles/other-user-profiles.component.html
src/app/other-user-profiles/other-user-profiles.component.spec.ts
src/app/other-user-skills/other-user-skills.component.html
src/app/other-user-skills/other-user-skills.component.scss
src/app/other-user-skills/other-user-skills.component.spec.ts
src/app/other-user-skills/other-user-skills.component.ts
src/app/skill-card/skill-card.component.html
src/app/skill-card/skill-card.component.scss
src/app/skill-card/skill-card.component.spec.ts
src/app/skill-card/skill-card.component.ts
src/app/skill-card/skill-view.ts
src/app/skill-card/user-skill-view.ts
src/app/users/users.service.spec.ts
src/app/users/users.service.ts

Show other users' skill profile

---

src/app/users/user-profile.component.ts

The error occurred while adding a new item into an empty list (industrySectors, languages etc.).

fix NPE while adding new elem into a list

---

src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.module.ts
src/app/communities/communities-edit.component.html
src/app/communities/communities-edit.component.scss
src/app/communities/communities-edit.component.spec.ts
src/app/communities/communities-edit.component.ts
src/app/communities/communities-new.component.html
src/app/communities/communities-new.component.scss
src/app/communities/communities-new.component.spec.ts
src/app/communities/communities-new.component.ts
src/app/communities/communities.component.html
src/app/communities/communities.component.scss
src/app/communities/communities.component.spec.ts
src/app/communities/communities.component.ts
src/app/communities/communities.service.spec.ts
src/app/communities/communities.service.ts
src/app/communities/community.ts
src/app/communities/link.ts

[FE] Implement components to manage communities

---

src/app/app-material.module.ts
src/app/app.module.ts
src/app/communities/closed-community-confirm-dialog.component.html
src/app/communities/closed-community-confirm-dialog.component.spec.ts
src/app/communities/closed-community-confirm-dialog.component.ts
src/app/communities/communities-edit.component.html
src/app/communities/communities-edit.component.scss
src/app/communities/communities-edit.component.spec.ts
src/app/communities/communities-edit.component.ts
src/app/communities/communities-filter.pipe.spec.ts
src/app/communities/communities-new.component.html
src/app/communities/communities-new.component.scss
src/app/communities/communities-new.component.spec.ts
src/app/communities/communities-new.component.ts
src/app/communities/communities.component.html
src/app/communities/communities.component.scss
src/app/communities/communities.component.spec.ts
src/app/communities/communities.component.ts
src/app/communities/communities.service.spec.ts
src/app/communities/community-type.enum.ts
src/app/communities/community.ts

@LebedkoDmitry could you please make a code review?

[FE] Displaying a communtity type

---

src/app/communities/communities-edit.component.html
src/app/communities/communities-edit.component.spec.ts
src/app/communities/communities-edit.component.ts
src/app/communities/communities-filter.pipe.spec.ts
src/app/communities/communities-filter.pipe.ts
src/app/communities/communities-new.component.html
src/app/communities/communities-new.component.spec.ts
src/app/communities/communities-new.component.ts
src/app/communities/communities.component.html
src/app/communities/communities.component.scss
src/app/communities/communities.component.ts
src/app/communities/communities.service.spec.ts
src/app/communities/communities.service.ts
src/app/communities/community-request.ts
src/app/communities/community-response.ts

@LebedkoDmitry could you please make a code review?

[FE] Displaying a list of available skills

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/communities/communities.component.html
src/app/communities/communities.component.spec.ts
src/app/communities/communities.component.ts
src/app/communities/communities.service.spec.ts
src/app/communities/communities.service.ts
src/app/community-view/community-view.component.html
src/app/community-view/community-view.component.scss
src/app/community-view/community-view.component.spec.ts
src/app/community-view/community-view.component.ts

community view page + leave community button

[FE] Opening a community to view

---

src/app/communities/communities-edit.component.html
src/app/communities/communities-edit.component.spec.ts
src/app/communities/communities-edit.component.ts
src/app/communities/communities-new.component.html
src/app/communities/communities-new.component.spec.ts
src/app/communities/communities-new.component.ts
src/app/communities/community-request.ts

[FE] Add a possibility to create a new skill in the chip-list

---

src/app/communities/communities.service.spec.ts
src/app/communities/communities.service.ts
src/app/community-view/community-view.component.html
src/app/community-view/community-view.component.scss
src/app/community-view/community-view.component.spec.ts
src/app/community-view/community-view.component.ts

[FE] Add a button to remove a community member

---

src/app/app-material.module.ts
src/app/app-routing.spec.ts
src/app/app.component.html
src/app/app.component.scss
src/app/app.component.spec.ts
src/app/app.module.ts
src/app/format-counter.pipe.spec.ts
src/app/format-counter.pipe.ts
src/app/shared/user-identity.ts

Badge-counter of pending invitations

---

src/app/communities/communities.component.html
src/app/communities/communities.component.scss
src/app/communities/communities.component.spec.ts
src/app/communities/community-response.ts

Recommended communities label

---

src/app/communities/communities-edit.component.html
src/app/communities/communities-edit.component.scss
src/app/communities/communities-edit.component.spec.ts
src/app/communities/communities-edit.component.ts
src/app/communities/communities-new.component.html
src/app/communities/communities-new.component.scss
src/app/communities/communities-new.component.spec.ts
src/app/communities/communities-new.component.ts
src/app/communities/communities.service.spec.ts
src/app/communities/community-request.ts

Control to invite users to join a community

---

src/app/my-skills/my-skills-new.component.html
src/app/my-skills/my-skills-new.component.spec.ts
src/app/my-skills/my-skills-new.component.ts
src/app/projects/projects-new.component.html
src/app/projects/projects-new.component.spec.ts
src/app/projects/projects-new.component.ts

my-skills, projects: disable save button while sending a create request
tests
@georgwittberger could you please take a look?

[SKOOP-92] Duplicate assignment of same skill to user

---

src/app/app.module.ts
src/app/communities/communities.component.html
src/app/communities/communities.component.scss
src/app/communities/communities.component.spec.ts
src/app/communities/communities.service.spec.ts
src/app/communities/communities.service.ts
src/app/recommended-communities/recommended-communities.component.html
src/app/recommended-communities/recommended-communities.component.scss
src/app/recommended-communities/recommended-communities.component.spec.ts
src/app/recommended-communities/recommended-communities.component.ts
src/app/shared/community-card/community-card.component.html
src/app/shared/community-card/community-card.component.scss
src/app/shared/community-card/community-card.component.spec.ts
src/app/shared/community-card/community-card.component.ts

component to display recommended communities
tests

[SKOOP-93] Recommended communities component

---

src/app/communities/communities-edit.component.html
src/app/communities/communities-edit.component.scss
src/app/communities/communities-edit.component.spec.ts
src/app/communities/communities-edit.component.ts

Removed control to invite users from the edit community dialog

[SKOOP-95] Remove control to invite users from the edit community dialog

---

src/app/communities/communities.component.spec.ts
src/app/communities/communities.component.ts
src/app/community-view/community-view.component.spec.ts
src/app/community-view/community-view.component.ts
src/app/recommended-communities/recommended-communities.component.html
src/app/recommended-communities/recommended-communities.component.spec.ts
src/app/recommended-communities/recommended-communities.component.ts

use POST /communities/{communityId}/user-registrations to create a request to join a closed community
tests

[SKOOP-108] Join a closed community

---

src/app/community-view/community-view.component.html
src/app/community-view/community-view.component.scss
src/app/community-view/community-view.component.ts

update list of members after kicking out 
fix css to properly display of the delete icon

[SKOOP-109] Reload list of members after kicking out

---

src/app/my-messages/messages.service.spec.ts
src/app/my-messages/messages.service.ts
src/app/my-messages/my-messages.component.spec.ts
src/app/my-messages/my-messages.component.ts

fixed a visibility of accept/decline buttons

[SKOOP-85] visibility of accept/decline buttons

---

src/app/community-view/community-invitation-dialog.component.html
src/app/community-view/community-invitation-dialog.component.scss
src/app/community-view/community-invitation-dialog.component.spec.ts
src/app/community-view/community-invitation-dialog.component.ts
src/app/community-view/community-view.component.ts
src/app/shared/community-user.service.spec.ts
src/app/shared/community-user.service.ts

displaying a list of recommended users
tests

[SKOOP-115] Displaying a list of recommended users

---

src/app/communities/communities.service.spec.ts
src/app/communities/communities.service.ts
src/app/community-view/community-user-role-request.ts
src/app/community-view/community-view.component.html
src/app/community-view/community-view.component.scss
src/app/community-view/community-view.component.spec.ts
src/app/community-view/community-view.component.ts
src/app/my-messages/community-role-changed-notification.ts
src/app/my-messages/my-messages.component.html
src/app/my-messages/my-messages.component.spec.ts
src/app/my-messages/notification-type.enum.ts

control to manage community user role
show label when the list of members is empty
rename enum values
tests

[SKOOP-113] Control to manage community user role

---

src/app/communities/communities-edit.component.spec.ts
src/app/communities/communities-edit.component.ts
src/app/communities/communities-filter.pipe.spec.ts
src/app/communities/communities.component.spec.ts
src/app/communities/communities.service.spec.ts
src/app/communities/link.ts
src/app/community-view/community-view.component.spec.ts
src/app/recommended-communities/recommended-communities.component.spec.ts

add id field to community links to prevent duplication of community links

[bugfix] add id field to community links

---

src/app/communities/communities.component.ts

hide join button after creating a community

[bugfix] hide join button after creating a community

---

src/app/my-messages/acceptance-to-community-notification.ts
src/app/my-messages/community-changed-notification.ts
src/app/my-messages/community-invitation-notification.ts
src/app/my-messages/join-community-request-notification.ts
src/app/my-messages/member-kicked-out-notification.ts
src/app/my-messages/member-left-community-notification.ts
src/app/my-messages/my-messages.component.html
src/app/my-messages/my-messages.component.spec.ts

The field "communityName" introduced for the notifications to provide name of the community in case the community was deleted.

[feature] added communityName field

---

src/app/my-messages/community-changed-notification.ts
src/app/my-messages/community-details.enum.ts
src/app/my-messages/my-messages.component.html
src/app/my-messages/my-messages.component.spec.ts
src/app/my-messages/notification-type.enum.ts

CommunityChangedNotification
tests

[SKOOP-119] CommunityChangedNotification

---

src/app/community-view/community-view.component.scss
src/app/my-messages/my-messages.component.html

the button 'View message' was removed.

[SKOOP-90] Remove 'View message' button

---

src/app/my-messages/abstract-notification.ts
src/app/my-messages/acceptance-to-community-notification.ts
src/app/my-messages/community-changed-notification.ts
src/app/my-messages/community-deleted-notification.ts
src/app/my-messages/community-invitation-notification.ts
src/app/my-messages/community-role-changed-notification.ts
src/app/my-messages/join-community-request-notification.ts
src/app/my-messages/member-kicked-out-notification.ts
src/app/my-messages/member-left-community-notification.ts
src/app/my-messages/messages.service.spec.ts
src/app/my-messages/messages.service.ts
src/app/my-messages/my-messages.component.html
src/app/my-messages/my-messages.component.spec.ts
src/app/my-messages/my-messages.component.ts

button to delete notification
tests

[SKOOP-121] button to delete notification

---

src/app/app-routing.spec.ts
src/app/app.component.html
src/app/app.component.ts
src/app/my-messages/my-messages.component.spec.ts
src/app/my-messages/my-messages.component.ts
src/app/shared/notification-counter.service.spec.ts
src/app/shared/notification-counter.service.ts

service to manage notification counts
tests
@LebedkoDmitry could uou please take a look?

[SKOOP-122] service to manage notification counts

---

src/app/community-view/community-view.component.ts
src/app/error/global-error-handler.service.spec.ts
src/app/recommended-communities/recommended-communities.component.ts
src/app/skill-groups/skill-groups-new.component.html
src/app/skill-groups/skill-groups-new.component.spec.ts
src/app/skill-groups/skill-groups.service.spec.ts
src/app/skill-users/skill-users.service.spec.ts
src/app/users/user-profile.component.spec.ts
src/app/users/user-profile.component.ts
src/app/users/user-request.ts

tests for GlobalErrorHandlerService, SkillGroupsService, SkillUsersService, SkillGroupsNewComponent

increase test coverage

---

src/app/app-material.module.ts
src/app/app.module.ts
src/app/shared/skill-select-input/skill-select-input.component.html
src/app/shared/skill-select-input/skill-select-input.component.scss
src/app/shared/skill-select-input/skill-select-input.component.spec.ts
src/app/shared/skill-select-input/skill-select-input.component.ts
src/app/testimonials/testimonial-request.ts
src/app/testimonials/testimonial-response.ts
src/app/testimonials/testimonial.service.spec.ts
src/app/testimonials/testimonial.service.ts
src/app/testimonials/testimonial.ts
src/app/testimonials/testimonials-new.component.html
src/app/testimonials/testimonials-new.component.scss
src/app/testimonials/testimonials-new.component.spec.ts
src/app/testimonials/testimonials-new.component.ts
src/app/testimonials/testimonials.component.html
src/app/testimonials/testimonials.component.scss
src/app/testimonials/testimonials.component.spec.ts
src/app/testimonials/testimonials.component.ts
src/app/users/user-profile.component.html
src/app/users/user-profile.component.scss
src/app/users/user-profile.component.spec.ts

control to add testimonials
move skills FormControl to the separate component
tests

[SKOOP-126] Control to add testimonials on the user

---

src/app/testimonials/testimonial.service.spec.ts
src/app/testimonials/testimonial.service.ts
src/app/testimonials/testimonials.component.html
src/app/testimonials/testimonials.component.scss
src/app/testimonials/testimonials.component.spec.ts
src/app/testimonials/testimonials.component.ts
src/app/users/user-profile.component.html
src/app/users/user-profile.component.scss

component to display user's testimonials
tests

[SKOOP-133] Component to display user's testimonials

---

src/app/communities/communities-edit.component.html
src/app/communities/communities-edit.component.spec.ts
src/app/communities/communities-edit.component.ts
src/app/communities/communities-new.component.html
src/app/communities/communities-new.component.spec.ts
src/app/communities/communities-new.component.ts

duplicated code in the community create/update dialog was replaced with SkillSelectInputStubComponent 

using SkillSelectInputStubComponent in a community create/update dialog

---

src/app/app.module.ts
src/app/shared/skill-select-input/skill-select-input.component.ts
src/app/testimonials/testimonial.service.spec.ts
src/app/testimonials/testimonial.service.ts
src/app/testimonials/testimonials-edit.component.html
src/app/testimonials/testimonials-edit.component.scss
src/app/testimonials/testimonials-edit.component.spec.ts
src/app/testimonials/testimonials-edit.component.ts
src/app/testimonials/testimonials.component.spec.ts
src/app/testimonials/testimonials.component.ts

Component to edit a testimonial
tests

[SKOOP-126] Component to edit a testimonial

---

src/app/app.module.ts
src/app/publications/publication-request.ts
src/app/publications/publication-response.ts
src/app/publications/publication.service.spec.ts
src/app/publications/publication.service.ts
src/app/publications/publication.ts
src/app/publications/publications-edit.component.html
src/app/publications/publications-edit.component.scss
src/app/publications/publications-edit.component.spec.ts
src/app/publications/publications-edit.component.ts
src/app/publications/publications-new.component.html
src/app/publications/publications-new.component.scss
src/app/publications/publications-new.component.spec.ts
src/app/publications/publications-new.component.ts
src/app/publications/publications.component.html
src/app/publications/publications.component.scss
src/app/publications/publications.component.spec.ts
src/app/publications/publications.component.ts
src/app/testimonials/testimonials.component.spec.ts
src/app/users/user-profile.component.html
src/app/users/user-profile.component.spec.ts
src/app/util/util.spec.ts
src/app/util/util.ts

Components to display, create, update publications
tests

[SKOOP-131] Components to display, create, update publications

---

src/app/app-routing.spec.ts
src/app/app.component.spec.ts
src/app/app.component.ts
src/app/my-messages/messages.service.ts
src/app/shared/notification-counter.service.spec.ts
src/app/shared/notification-counter.service.ts
src/app/shared/user-identity.ts

reworked NotificationCounterService.getCount method
updated tests

[SKOOP-139] Notification counter

---

src/app/app.module.ts
src/app/memberships/membership-request.ts
src/app/memberships/membership-response.ts
src/app/memberships/membership.service.spec.ts
src/app/memberships/membership.service.ts
src/app/memberships/membership.ts
src/app/memberships/memberships-edit.component.html
src/app/memberships/memberships-edit.component.scss
src/app/memberships/memberships-edit.component.spec.ts
src/app/memberships/memberships-edit.component.ts
src/app/memberships/memberships-new.component.html
src/app/memberships/memberships-new.component.scss
src/app/memberships/memberships-new.component.spec.ts
src/app/memberships/memberships-new.component.ts
src/app/memberships/memberships.component.html
src/app/memberships/memberships.component.scss
src/app/memberships/memberships.component.spec.ts
src/app/memberships/memberships.component.ts
src/app/users/user-profile.component.html
src/app/users/user-profile.component.spec.ts

added components to create/view/update user's membership
tests

[SKOOP-137] Components to create/view/update user's membership

---

src/app/shared/skill-select-input/skill-select-input.component.spec.ts
src/app/shared/skill-select-input/skill-select-input.component.ts

Adding an empty skill is not allowed now.

fix bug with adding an empty skill

---

src/app/memberships/memberships.component.html
src/app/publications/publications-edit.component.html
src/app/publications/publications-new.component.html

display link as link
skills field is always second

Improvement in the user profile view

---

src/app/my-projects/my-projects-edit.component.html
src/app/my-projects/my-projects-edit.component.spec.ts
src/app/my-projects/my-projects-edit.component.ts
src/app/my-projects/my-projects-new.component.html
src/app/my-projects/my-projects-new.component.spec.ts
src/app/my-projects/my-projects-new.component.ts
src/app/my-projects/my-projects.component.html
src/app/my-projects/my-projects.component.scss
src/app/my-projects/my-projects.component.spec.ts
src/app/my-projects/my-projects.service.spec.ts
src/app/user-projects/assign-user-project-request.ts
src/app/user-projects/update-user-project-request.ts
src/app/user-projects/user-project.ts
src/app/user-projects/user-projects.service.spec.ts
src/app/util/util.spec.ts

Skills field was added
ProjectName field was changed to text field

[SKOOP-104] Skills in MyProjects

---

src/app/my-projects/my-projects-new.component.ts

ignoring timezone in a userproject's startDate/endDate 

[bugfix] fix passing a date while creating an user project

---

src/app/my-messages/abstract-notification.ts
src/app/my-messages/my-messages.component.html
src/app/my-messages/my-messages.component.spec.ts
src/app/my-messages/my-messages.component.ts
src/app/my-messages/notification-type.enum.ts
src/app/my-messages/user-welcome-notification.ts
src/app/shared/info-dialog/info-dialog.component.html
src/app/shared/template-loader.service.spec.ts
src/app/shared/template-loader.service.ts
src/app/util/util.spec.ts
src/app/util/util.ts
src/assets/templates/welcome-notification.html

Displaying welcome-notification in MyMessages page

[SKOOP-145] Welcome notification

---

src/app/app-material.module.ts
src/app/memberships/memberships.component.spec.ts
src/app/memberships/memberships.component.ts
src/app/permissions/permissions.component.spec.ts
src/app/permissions/permissions.component.ts
src/app/publications/publications.component.spec.ts
src/app/publications/publications.component.ts
src/app/shared/popup-notification-class-name.enum.ts
src/app/shared/popup-notification.service.spec.ts
src/app/shared/popup-notification.service.ts
src/app/testimonials/testimonials.component.spec.ts
src/app/testimonials/testimonials.component.ts
src/app/users/user-profile.component.spec.ts
src/app/users/user-profile.component.ts
src/styles.scss

A service for openning success/warning/error popup notifications was added. 
Popup notification is displayed after each successfully executed create/update/delete operation for each section of the "My Profile" page.
@georgwittberger, @LebedkoDmitry could you please take a look?

[SKOOP-143] Success messages for the user profile page

---

src/app/app.module.ts
src/app/my-messages/my-messages.component.html
src/app/my-messages/my-messages.component.spec.ts
src/app/my-messages/notification-type.enum.ts
src/app/my-messages/skills-estimation-message-card/skills-estimation-message-card.component.html
src/app/my-messages/skills-estimation-message-card/skills-estimation-message-card.component.scss
src/app/my-messages/skills-estimation-message-card/skills-estimation-message-card.component.spec.ts
src/app/my-messages/skills-estimation-message-card/skills-estimation-message-card.component.ts
src/app/my-messages/skills-estimation-message-card/skills-estimation-notification.ts

Displaying 'skills estimation' notification on the MyMessages page.

[SKOOP-162] Displaying 'skills estimation' notification on the MyMessages page

---

src/app/app.module.ts
src/app/user-manager/manager.service.spec.ts
src/app/user-manager/manager.service.ts
src/app/user-manager/user-manager.component.html
src/app/user-manager/user-manager.component.scss
src/app/user-manager/user-manager.component.spec.ts
src/app/user-manager/user-manager.component.ts
src/app/users/user-profile.component.html
src/app/users/user-profile.component.spec.ts
src/app/users/user.ts

Displaying the manager of the current user on the MyProfile page

[SKOOP-170] Displaying the manager of the current user on the MyProfile

---

src/app/app-routing.module.ts
src/app/app.component.html
src/app/app.module.ts
src/app/my-subordinates/my-subordinates.component.html
src/app/my-subordinates/my-subordinates.component.scss
src/app/my-subordinates/my-subordinates.component.spec.ts
src/app/my-subordinates/my-subordinates.component.ts
src/app/shared/manager.service.spec.ts
src/app/shared/manager.service.ts
src/app/user-manager/user-manager.component.spec.ts
src/app/user-manager/user-manager.component.ts

Page to display list of the subordinates of the current user.
tests

[SKOOP-171] 'My subordinates' page

---

src/app/app-routing.module.ts
src/app/app.module.ts
src/app/my-projects/my-projects.component.html
src/app/my-projects/my-projects.component.scss
src/app/my-projects/my-projects.component.spec.ts
src/app/my-subordinates/my-subordinates.component.html
src/app/my-subordinates/my-subordinates.component.spec.ts
src/app/my-subordinates/my-subordinates.component.ts
src/app/project-memberships/project-memberships.component.html
src/app/project-memberships/project-memberships.component.scss
src/app/project-memberships/project-memberships.component.spec.ts
src/app/project-memberships/project-memberships.component.ts
src/app/shared/user-project-card/user-project-card.component.html
src/app/shared/user-project-card/user-project-card.component.scss
src/app/shared/user-project-card/user-project-card.component.spec.ts
src/app/shared/user-project-card/user-project-card.component.ts

UserProjectCardComponent
component to display projects of subordinates 

[SKOOP-174] Page to allow a manager to view the projects of his subordinates

---

src/app/my-projects/my-projects-edit.component.spec.ts
src/app/my-projects/my-projects.component.spec.ts
src/app/my-projects/my-projects.service.spec.ts
src/app/shared/user-project-card/user-project-card.component.html
src/app/shared/user-project-card/user-project-card.component.scss
src/app/shared/user-project-card/user-project-card.component.spec.ts
src/app/user-projects/user-project.ts
src/app/user-projects/user-projects.service.spec.ts
src/app/util/util.spec.ts

'Requires approval' flag was added on user-project card.

[SKOOP-180] 'Requires approval' flag

---

src/app/app.module.ts
src/app/my-messages/approve-project-message-card/approve-project-message-card.component.html
src/app/my-messages/approve-project-message-card/approve-project-message-card.component.scss
src/app/my-messages/approve-project-message-card/approve-project-message-card.component.spec.ts
src/app/my-messages/approve-project-message-card/approve-project-message-card.component.ts
src/app/my-messages/approve-project-message-card/project-requires-approval-notification.ts
src/app/my-messages/my-messages.component.html
src/app/my-messages/my-messages.component.spec.ts
src/app/my-messages/notification-type.enum.ts

'Project membership requires approval' notification was added

[SKOOP-181] 'Project membership requires approval' notification

---

src/app/project-memberships/project-memberships.component.html
src/app/project-memberships/project-memberships.component.spec.ts
src/app/project-memberships/project-memberships.component.ts
src/app/user-projects/update-user-project-request.ts

Button to approve the project of subordinate was added.
tests

[SKOOP-183] Button to approve the project

---

src/app/my-messages/approve-project-message-card/approve-project-message-card.component.html
src/app/my-messages/approve-project-message-card/approve-project-message-card.component.ts
src/app/my-messages/community-acceptance-message-card/community-acceptance-message-card.component.html
src/app/my-messages/community-acceptance-message-card/community-acceptance-message-card.component.spec.ts
src/app/my-messages/community-acceptance-message-card/community-acceptance-message-card.component.ts
src/app/my-messages/community-changed-message-card/community-changed-message-card.component.html
src/app/my-messages/community-changed-message-card/community-changed-message-card.component.spec.ts
src/app/my-messages/community-changed-message-card/community-changed-message-card.component.ts
src/app/my-messages/community-invitation-message-card/community-invitation-message-card.component.html
src/app/my-messages/community-invitation-message-card/community-invitation-message-card.component.spec.ts
src/app/my-messages/community-join-request-message-card/community-join-request-message-card.component.html
src/app/my-messages/community-join-request-message-card/community-join-request-message-card.component.spec.ts
src/app/my-messages/community-kick-out-message-card/community-kick-out-message-card.component.html
src/app/my-messages/community-kick-out-message-card/community-kick-out-message-card.component.spec.ts
src/app/my-messages/community-kick-out-message-card/community-kick-out-message-card.component.ts
src/app/my-messages/community-left-message-card/community-left-message-card.component.html
src/app/my-messages/community-left-message-card/community-left-message-card.component.spec.ts
src/app/my-messages/community-left-message-card/community-left-message-card.component.ts
src/app/my-messages/skills-estimation-message-card/skills-estimation-message-card.component.html
src/app/my-messages/skills-estimation-message-card/skills-estimation-message-card.component.spec.ts
src/app/my-messages/skills-estimation-message-card/skills-estimation-message-card.component.ts
src/app/my-messages/todo-notification-component-trait.ts

replace href with routerLink in the notification cards
tests

[SKOOP-185] Open internal links without reloading the page

---

src/app/project-memberships/project-memberships.component.html

Info message is displayed when a subordinate has no projects.

[SKOOP-161] Info message when a subordinate has no projects

---

src/app/app.component.ts
src/app/my-messages/my-messages.component.spec.ts
src/app/my-messages/my-messages.component.ts
src/app/project-memberships/project-memberships.component.html
src/app/project-memberships/project-memberships.component.spec.ts
src/app/project-memberships/project-memberships.component.ts
src/app/shared/notification-counter.service.spec.ts
src/app/shared/notification-counter.service.ts

Improved message loading mechanism.
Counter update after project approval

[SKOOP-164] Update message count after project approval

---

src/app/my-skills/my-skills-edit.component.html
src/app/my-skills/my-skills-edit.component.spec.ts
src/app/my-skills/my-skills-edit.component.ts
src/app/my-skills/my-skills-new.component.html
src/app/my-skills/my-skills-new.component.spec.ts
src/app/my-skills/my-skills-new.component.ts
src/assets/config/priority-description.json

Description is displayed for selected priority value and for skill priority label.
@georgwittberger could you please take a look?

[SKOOP-191] Description for prioritization of skills

---

src/app/app.module.ts
src/app/user-profile-search/user-profile-search-result.ts
src/app/user-profile-search/user-profile-search-result/user-profile-search-result.component.html
src/app/user-profile-search/user-profile-search-result/user-profile-search-result.component.scss
src/app/user-profile-search/user-profile-search-result/user-profile-search-result.component.spec.ts
src/app/user-profile-search/user-profile-search-result/user-profile-search-result.component.ts
src/app/user-profile-search/user-profile-search.component.html
src/app/user-profile-search/user-profile-search.component.scss
src/app/user-profile-search/user-profile-search.component.spec.ts
src/app/user-profile-search/user-profile-search.component.ts
src/app/user-profile-search/user-profile-search.service.spec.ts
src/app/user-profile-search/user-profile-search.service.ts
src/app/users/user.ts
src/assets/mock/search-result.json

Component to display a list of found users (for now mocked data is used)
@georgwittberger could you please take a look?

[SKOOP-211] Presentation search result

---

src/app/my-skills/my-skills-edit.component.spec.ts
src/app/my-skills/my-skills-edit.component.ts
src/app/my-skills/my-skills-new.component.spec.ts
src/app/my-skills/my-skills.component.html
src/app/my-skills/my-skills.component.spec.ts
src/app/my-skills/my-skills.component.ts
src/app/my-skills/my-skills.service.ts
src/app/my-skills/update-user-skill-request.ts
src/app/shared/skill-card/user-skill-view.ts
src/app/user-skills/user-skill.ts
src/app/user-skills/user-skills.service.spec.ts
src/app/user-skills/user-skills.service.ts

Button to mark a skill as favorite/ to remove from favorites
tests

[SKOOP-93] Mark skills as favorites
